-- Compatibility migration for old furniture_store databases.
-- It is intentionally additive and safe for repeated local runs.

ALTER TABLE `user` MODIFY COLUMN `role` VARCHAR(30) NOT NULL DEFAULT 'CUSTOMER';
UPDATE `user` SET `role` = REPLACE(UPPER(`role`), 'ROLE_', '') WHERE `role` IS NOT NULL;

ALTER TABLE `user` ADD COLUMN `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `user` ADD COLUMN `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE `user` ADD COLUMN `created_by` VARCHAR(255) DEFAULT 'system';
ALTER TABLE `user` ADD COLUMN `updated_by` VARCHAR(255) NULL;
ALTER TABLE `user` ADD COLUMN `active` BIT(1) NOT NULL DEFAULT b'1';
ALTER TABLE `user` ADD COLUMN `email` VARCHAR(120) NULL;
ALTER TABLE `user` ADD COLUMN `full_name` VARCHAR(120) NULL;
ALTER TABLE `user` ADD COLUMN `email_verified` BIT(1) NOT NULL DEFAULT b'1';
ALTER TABLE `user` ADD COLUMN `account_non_locked` BIT(1) NOT NULL DEFAULT b'1';

ALTER TABLE `product` ADD COLUMN `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `product` ADD COLUMN `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE `product` ADD COLUMN `created_by` VARCHAR(255) DEFAULT 'system';
ALTER TABLE `product` ADD COLUMN `updated_by` VARCHAR(255) NULL;
ALTER TABLE `product` ADD COLUMN `active` BIT(1) NOT NULL DEFAULT b'1';
ALTER TABLE `product` ADD COLUMN `material` VARCHAR(80) NULL;
ALTER TABLE `product` ADD COLUMN `color` VARCHAR(60) NULL;
ALTER TABLE `product` ADD COLUMN `dimensions` VARCHAR(80) NULL;
ALTER TABLE `product` ADD COLUMN `condition_status` VARCHAR(50) DEFAULT 'NEW';
ALTER TABLE `product` ADD COLUMN `status` VARCHAR(30) DEFAULT 'ACTIVE';
ALTER TABLE `product` ADD COLUMN `stock_threshold` BIGINT DEFAULT 5;
ALTER TABLE `product` ADD COLUMN `weight_kg` DOUBLE NULL;
ALTER TABLE `product` ADD COLUMN `category_id` BIGINT NULL;

ALTER TABLE `cart` ADD COLUMN `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `cart` ADD COLUMN `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE `cart` ADD COLUMN `created_by` VARCHAR(255) DEFAULT 'system';
ALTER TABLE `cart` ADD COLUMN `updated_by` VARCHAR(255) NULL;
ALTER TABLE `cart` ADD COLUMN `active` BIT(1) NOT NULL DEFAULT b'1';

ALTER TABLE `cart_item` ADD COLUMN `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `cart_item` ADD COLUMN `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE `cart_item` ADD COLUMN `created_by` VARCHAR(255) DEFAULT 'system';
ALTER TABLE `cart_item` ADD COLUMN `updated_by` VARCHAR(255) NULL;
ALTER TABLE `cart_item` ADD COLUMN `active` BIT(1) NOT NULL DEFAULT b'1';

CREATE TABLE IF NOT EXISTS `product_tags` (`product_id` BIGINT NOT NULL, `tag_id` BIGINT NOT NULL);
DELETE pt FROM `product_tags` pt LEFT JOIN `product` p ON p.id = pt.product_id WHERE p.id IS NULL;
DELETE pt FROM `product_tags` pt LEFT JOIN `tags` t ON t.id = pt.tag_id WHERE t.id IS NULL;

CREATE TABLE IF NOT EXISTS `audit_logs` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `actor` VARCHAR(120) NOT NULL DEFAULT 'system',
  `action` VARCHAR(80) NOT NULL,
  `entity_name` VARCHAR(80) NOT NULL,
  `entity_id` BIGINT NULL,
  `details` VARCHAR(1000) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);
ALTER TABLE `audit_logs` ADD COLUMN `actor` VARCHAR(120) NOT NULL DEFAULT 'system';
ALTER TABLE `audit_logs` ADD COLUMN `action` VARCHAR(80) NOT NULL DEFAULT 'UNKNOWN';
ALTER TABLE `audit_logs` ADD COLUMN `entity_name` VARCHAR(80) NOT NULL DEFAULT 'Unknown';
ALTER TABLE `audit_logs` ADD COLUMN `entity_id` BIGINT NULL;
ALTER TABLE `audit_logs` ADD COLUMN `details` VARCHAR(1000) NULL;
ALTER TABLE `audit_logs` ADD COLUMN `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
